services:

  backend:
    build:
      context: .
    secrets:
      - db-password
      - opendota-api-key
    environment:
      - DB_HOST=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD_PATH=/run/secrets/db-password
      - DB_NAME=main
      - OPEN_DOTA_API_KEY_PATH=/run/secrets/opendota-api-key
      - REDIS_ADDR=redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=main
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    # expose:
    #   - 5432
    ports:
      - 54320:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  proxy:
    image: nginx
    restart: always
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on: 
      - backend

  asynq_ui:
    image: hibiken/asynqmon
    ports:
      - 8080:8080
    environment:
      - REDIS_ADDR=redis:6379
    depends_on: 
      - backend

volumes:
  db-data:

secrets:
  db-password:
    file: secrets/db-password
  opendota-api-key:
    file: secrets/opendota-api-key